from harness import Harness,TESTS
from browser_matrix import click_attr
import json
h=Harness();rows=[]
try:
 p=h.app();p.add_script_tag(content=(TESTS/'fixtures.js').read_text());p.add_script_tag(content=(TESTS/'pipeline_fixtures.js').read_text());levels=p.evaluate('CEFR_LEVELS')
 for level in levels:
  p.evaluate('auditReset(["translation"],"instant","en");goTo(1)');click_attr(p,'onclick',"toggleCefr('"+level+"')");assert p.evaluate('state.uroven')==[level];x=p.evaluate('async()=>{const b=await assembleTestHtml(state,auditFixtures(state,"en"));return lastAssembled.cfg.cefr}');rows.append({'case':'CEFR-select-assemble','level':level,'ok':x==level})
 combos=p.evaluate('''()=>{const result=[];for(let mask=1;mask<(1<<CEFR_LEVELS.length);mask++){state.kombinovat=true;state.uroven=CEFR_LEVELS.filter((_,i)=>mask&(1<<i));const expected=state.uroven.join('/');const label=cefrLabel();toggleKombinovat();result.push({mask,expected,label,kept:state.uroven[0],ok:label===expected&&state.uroven.length===1&&state.uroven[0]===expected.split('/').at(-1)});}return result}''');rows+=combos
 checks=p.evaluate('''()=>{const out=[];for(const typ of ALL_TYPES)for(const points of [0,-1,0.5,1,999,1000]){auditConfigure([typ],'instant','en');state.exerciseConfig[0].body=points;let allowed=true;try{generationPlan(state)}catch{allowed=false}out.push({case:'points-boundary',type:typ,points,ok:allowed===(Number.isInteger(points)&&points>=1&&points<=999)})}return out}''');rows+=checks
 for label,scale,expected in [('complete','A = 90-100 %\nB = 0-89 %',True),('gap','A = 90-100 %\nB = 0-80 %',False),('overlap','A = 80-100 %\nB = 0-90 %',False)]:
  got=p.evaluate('s=>{auditReset(["translation"],"instant","en");state.gradeTyp="vlastni";$("vlastniSkala").value=s;validate();return !$("next2").disabled}',scale);rows.append({'case':'custom-scale-'+label,'ok':got==expected,'allowed':got})
 # A transcript on an inactive source tab cannot silently validate an absent listening source.
 got=p.evaluate('()=>{auditConfigure(["listening comprehension"],"instant","en");state.listeningTranscript="";$("listeningTranscript").value="";state.zadaniTab="text";state.zadaniText="";state.urls=["https://example.invalid/source"];return hasListeningSource()}');rows.append({'case':'inactive-URL-not-listening-source','ok':not got})
 d=p.evaluate("""()=>{auditConfigure(['reading comprehension','listening comprehension'],'instant','en');state.readingQuestionCount=6;state.listeningQuestionCount=5;state.exerciseDetail=false;const simple={reading:defaultItemCount('reading comprehension',state),listening:defaultItemCount('listening comprehension',state)};state.exerciseDetail=true;state.exerciseConfig=[{typ:'reading comprehension',pocetOtazek:6,body:6,manualMode:false},{typ:'listening comprehension',pocetOtazek:5,body:5,manualMode:false}];setComprehensionQuestionCount('reading comprehension',7);setComprehensionQuestionCount('listening comprehension',4);return {simple,detail:state.exerciseConfig.map(x=>x.pocetOtazek),state:[state.readingQuestionCount,state.listeningQuestionCount]}}""");rows.append({'case':'comprehension-count-single-source','ok':d=={'simple':{'reading':6,'listening':5},'detail':[7,4],'state':[7,4]},'data':d})
 d=p.evaluate("""()=>{auditConfigure(['translation'],'instant','en');state.differentiationLevel='basic';const basic=buildContentPrompt(state,[]);state.differentiationLevel='challenge';const challenge=buildContentPrompt(state,[]);return {basic:basic.includes('SUPPORT / DIFFICULTY LEVEL = BASIC SUPPORT')&&basic.includes('SAME tested curriculum')&&basic.includes('item counts and point totals'),challenge:challenge.includes('SUPPORT / DIFFICULTY LEVEL = CHALLENGE')&&challenge.includes('SAME tested curriculum')&&challenge.includes('item counts and point totals')}}""");rows.append({'case':'difficulty-level-reaches-main-prompt','ok':d['basic'] and d['challenge'],'data':d})
 d=p.evaluate("""()=>{state.zadaniTab='url';state.urls=['https://youtu.be/abc123','https://www.youtube.com/watch?v=xyz987','https://example.com/article'];const x=buildGeminiUrlPartsForApi(state);return {youtube:x.youtubeUrls,context:x.contextUrls,useUrlContext:x.useUrlContext,parts:x.parts}}""");rows.append({'case':'youtube-uses-video-input-not-url-context','ok':len(d['youtube'])==2 and d['context']==['https://example.com/article'] and d['useUrlContext'] and len(d['parts'])==2 and all(('fileData' in x and 'fileUri' in x['fileData']) for x in d['parts']),'data':d})
 d=p.evaluate("""()=>{state.zadaniTab='url';state.urls=['https://youtu.be/onlyvideo'];const x=buildGeminiUrlPartsForApi(state);return {useUrlContext:x.useUrlContext,parts:x.parts}}""");rows.append({'case':'youtube-only-disables-url-context','ok':not d['useUrlContext'] and len(d['parts'])==1,'data':d})
 (TESTS.parent/'evidence/config-extra-suite.json').write_text(json.dumps(rows,indent=2));print(json.dumps({'runs':len(rows),'failures':[r for r in rows if not r['ok']]}))
finally:h.close()
