from harness import Harness,TESTS
import json,traceback
h=Harness();rows=[];out=TESTS.parent/'evidence/state-transition-suite.json'
def record(name,fn):
 row={'case':name}
 try:row.update(fn()or{},ok=True)
 except Exception as e:row.update(ok=False,error=str(e),trace=traceback.format_exc())
 rows.append(row);out.write_text(json.dumps(rows,indent=2,ensure_ascii=False));print(json.dumps({k:v for k,v in row.items()if k!='trace'},ensure_ascii=False),flush=True)
try:
 p=h.app();p.add_script_tag(content=(TESTS/'fixtures.js').read_text());p.add_script_tag(content=(TESTS/'pipeline_fixtures.js').read_text())
 def reset():
  p.evaluate("()=>{localStorage.clear();sessionStorage.clear();auditReset(['translation','multiple choice'],'instant','en');rosterEntries.length=0;setVal('ucitelPin','');setVal('heslo','');setVal('nazev','Transition QA');setVal('latka','Water');state.urls=[''];state.fileNames=[];state.rcTopic='';applyVisualState();validate();}")
 def adv_simple():
  reset();p.evaluate("()=>{state.appMode='advanced';state.workPreset='advanced';state.identityMode='oneTimeCode';rosterEntries.push({email:'student@example.invalid',label:'Student',code:'GHOST-123'});state.diferencovany='ANO';state.skupiny=[{id:9,nazev:'A',podminky:'weak',studenti:['Student One']}];state.exerciseDetail=true;state.exerciseConfig=[{typ:'translation',pocetOtazek:9,body:17,manualMode:false},{typ:'multiple choice',pocetOtazek:8,body:13,manualMode:false}];state.splitGenerate=true;state.layout='scroll';state.sourceUseMode='grammar';applyVisualState();}");p.evaluate("()=>{setAppMode('simple')}");p.locator('#uiModal [data-ui-ok]').click();p.wait_for_function("state.appMode==='simple'");d=p.evaluate("({mode:state.appMode,identity:state.identityMode,groups:state.skupiny.length,roster:rosterEntries.length,cfg:state.exerciseConfig.length,detail:state.exerciseDetail,split:state.splitGenerate,layout:state.layout,source:state.sourceUseMode,name:val('nazev'),topic:val('latka')})");assert d=={'mode':'simple','identity':'name','groups':0,'roster':0,'cfg':0,'detail':False,'split':False,'layout':'tabs','source':'auto','name':'Transition QA','topic':'Water'},d;return d
 record('advanced-to-simple-clears-hidden-state',adv_simple)
 def cancel():
  reset();p.evaluate("()=>{state.appMode='advanced';state.workPreset='advanced';state.diferencovany='ANO';state.skupiny=[{id:1,nazev:'Keep',podminky:'x',studenti:['S']}];state.exerciseDetail=true;state.exerciseConfig=[{typ:'translation',pocetOtazek:7,body:11,manualMode:false}];applyVisualState();window.__before=JSON.stringify(state)}");p.evaluate("()=>{setAppMode('simple')}");p.locator('#uiModal [data-ui-cancel]').click();same=p.evaluate("JSON.stringify(state)===window.__before");assert same;return {'unchanged':same}
 record('cancel-mode-switch-preserves-state',cancel)
 def roundtrip():
  reset();p.evaluate("()=>{state.appMode='simple';state.workPreset='quick';applySimpleDefaults();applyVisualState()}");p.evaluate("()=>{setAppMode('advanced')}");p.wait_for_function("state.appMode==='advanced'");p.evaluate("()=>{state.identityMode='oneTimeCode';rosterEntries.push({email:'x@example.invalid',label:'X',code:'ABC'});state.diferencovany='ANO';state.skupiny=[{id:2,nazev:'X',podminky:'x',studenti:['X']}];state.exerciseDetail=true;state.exerciseConfig=[{typ:'translation',pocetOtazek:6,body:9,manualMode:false}];}");p.evaluate("()=>{setAppMode('simple')}");p.locator('#uiModal [data-ui-ok]').click();p.wait_for_function("state.appMode==='simple'");p.evaluate("()=>{setAppMode('advanced')}");d=p.evaluate("({groups:state.skupiny.length,roster:rosterEntries.length,cfg:state.exerciseConfig.length,detail:state.exerciseDetail,diff:state.diferencovany,identity:state.identityMode})");assert d=={'groups':0,'roster':0,'cfg':0,'detail':False,'diff':'NE','identity':'name'},d;return d
 record('simple-advanced-simple-no-ghost-return',roundtrip)
 def snapshot():
  reset();p.evaluate("()=>{state.appMode='simple';state.workPreset='quick';state.fileNames=['secret.pdf'];setVal('ucitelPin','TOP-SECRET');setVal('heslo','TOP-SECRET');setVal('nazev','Saved test');setVal('zadaniText','Safe source text');currentStep=2;maxStep=3;const dom={};DOM_FIELDS.forEach(id=>dom[id]=val(id));localStorage.setItem(SAVE_KEY,JSON.stringify({dom,state:getStoredState(),currentStep,maxStep,ts:Date.now()}));state.appMode='advanced';state.fileNames=['changed.pdf'];setVal('ucitelPin','CHANGED');setVal('nazev','Changed');}");ok=p.evaluate("loadSnapshot()");d=p.evaluate("({mode:state.appMode,files:state.fileNames,pin:val('ucitelPin'),legacy:val('heslo'),name:val('nazev'),source:val('zadaniText'),step:currentStep,max:maxStep})");assert ok and d=={'mode':'simple','files':[],'pin':'','legacy':'','name':'Saved test','source':'Safe source text','step':2,'max':3},d;return d
 record('snapshot-roundtrip-clears-sensitive-and-files',snapshot)
 def template():
  reset();d=p.evaluate("""()=>{state.appMode='advanced';state.workPreset='advanced';state.diferencovany='ANO';state.skupiny=[{id:1,nazev:'Group A',podminky:'secret condition',studenti:['Alice','Bob']}];state.fileNames=['private.pdf'];state.urls=['https://example.test/source'];state.zadaniTab='url';state.rcTopic='Technology and society';state.readingQuestionCount=6;state.listeningQuestionCount=5;setVal('ucitelPin','PIN-SECRET');setVal('heslo','PASSWORD-SECRET');setVal('nazev','Template title');setVal('proKoho','3A4');setVal('latka','Past perfect');setVal('readingText','Readable source');setVal('listeningTranscript','Private-to-teacher transcript');const tpl={id:777,name:'QA template',format:'prefill_v3',prefill:getTemplatePrefill(),dom:getTemplateDomPrefill(),ts:Date.now()};const serialized=JSON.stringify(tpl);saveTemplates([tpl]);setVal('nazev','Changed');setVal('proKoho','Changed');setVal('latka','Changed');setVal('readingText','Changed');setVal('listeningTranscript','Changed');state.urls=['https://changed.invalid'];state.rcTopic='';state.readingQuestionCount=3;state.listeningQuestionCount=3;state.fileNames=['changed.pdf'];loadTemplate(777);return {serialized,name:val('nazev'),className:val('proKoho'),topic:val('latka'),reading:val('readingText'),transcript:val('listeningTranscript'),urls:state.urls,rcTopic:state.rcTopic,readingCount:state.readingQuestionCount,listeningCount:state.listeningQuestionCount,files:state.fileNames,pin:val('ucitelPin'),legacy:val('heslo'),groups:state.skupiny.map(g=>({name:g.nazev,conditions:g.podminky,students:g.studenti}))}}""");assert all(v not in d['serialized'] for v in ['PIN-SECRET','PASSWORD-SECRET','private.pdf','Alice','Bob','secret condition']),d;assert d['name']=='Template title' and d['className']=='3A4' and d['topic']=='Past perfect' and d['reading']=='Readable source' and d['transcript']=='Private-to-teacher transcript',d;assert d['urls']==['https://example.test/source'] and d['rcTopic']=='Technology and society' and d['readingCount']==6 and d['listeningCount']==5,d;assert d['files']==[] and d['pin']=='' and d['legacy']=='',d;assert d['groups']==[{'name':'Group A','conditions':'','students':[]}],d;return {'restored':True,'rcTopicRestored':True,'sensitiveExcluded':True,'filesCleared':True}
 record('template-prefill-v3-restores-safe-fields-only',template)
 def template_attachment():
  reset();d=p.evaluate("""async()=>{state.zadaniTab='file';state.fileNames=['lesson.pdf'];fileObjects=[{name:'lesson.pdf',type:'application/pdf'}];const oldPrompt=uiPrompt;let calls=0;uiPrompt=async()=>++calls===1?'Attachment template':'';try{await saveTemplate()}finally{uiPrompt=oldPrompt}const tpl=loadTemplates().at(-1);state.fileNames=['ghost.pdf'];fileObjects=[{name:'ghost.pdf'}];loadTemplate(tpl.id);const toast=[...document.querySelectorAll('#uiToastStack .ui-toast')].at(-1);const first={attachmentWasPresent:tpl.attachmentWasPresent,serialized:JSON.stringify(tpl),files:state.fileNames,fileObjects:fileObjects.length,tab:state.zadaniTab,toast:toast?.textContent||'',toastWarn:!!toast?.classList.contains('warn')};const legacy={...tpl,id:tpl.id+1};delete legacy.attachmentWasPresent;saveTemplates([legacy]);loadTemplate(legacy.id);const legacyToast=[...document.querySelectorAll('#uiToastStack .ui-toast')].at(-1);return {...first,legacyToast:legacyToast?.textContent||'',legacyWarn:!!legacyToast?.classList.contains('warn')}}""");assert d['attachmentWasPresent'] is True,d;assert 'lesson.pdf' not in d['serialized'],d;assert d['files']==[] and d['fileObjects']==0 and d['tab']=='file',d;assert 'Původní příloha se do šablony neukládá' in d['toast'] and 'připoj ji znovu' in d['toast'] and d['toastWarn'],d;assert 'Původní příloha se do šablony neukládá' in d['legacyToast'] and d['legacyWarn'],d;return d
 record('template-prefill-v3-warns-to-reattach-file',template_attachment)
 def diff_prompt_parity():
  reset()
  d=p.evaluate("""()=>{auditConfigure(['translation','multiple choice'],'instant','en');const out={};for(const level of ['basic','standard','challenge']){state.differentiationLevel=level;out[level]={main:buildContentPrompt(state,[]),legacy:buildPrompt()}}return out}""")
  for level in ['basic','standard','challenge']:
   legacy=d[level]['legacy'];main=d[level]['main']
   assert 'typy cvičení' in legacy and 'počty položek' in legacy and 'bodov' in legacy,{'level':level,'legacy':legacy[-2500:]}
   assert 'exercise types' in main and 'item counts' in main and ('point totals' in main or ' and points' in main),{'level':level,'main':main[-2500:]}
   assert 'méně nebo kratší položky' not in legacy and 'vyšší podíl produkčních úloh' not in legacy,{'level':level}
  return {'levels':['basic','standard','challenge'],'sameStructureInvariant':True,'legacyConflictRemoved':True}
 record('differentiation-prompts-preserve-structure',diff_prompt_parity)
 def history():
  reset();p.evaluate("()=>{state.appMode='advanced';state.workPreset='advanced';state.diferencovany='ANO';state.skupiny=[{id:1,nazev:'Group A',podminky:'support',studenti:['Alice Person','Bob Person']}];state.fileNames=['private.pdf'];setVal('ucitelPin','PIN-SECRET');pushHistory('Safe prompt without secrets')}");d=p.evaluate("()=>{const h=loadHistory()[0];return {text:JSON.stringify(h),students:h.state.skupiny[0].studenti,files:h.state.fileNames}}");assert all(v not in d['text'] for v in ['PIN-SECRET','Alice Person','Bob Person','private.pdf']) and d['students']==['Student A1','Student A2'] and d['files']==[],d;return {'students':d['students'],'files':d['files']}
 record('history-anonymizes-students-and-files',history)
 def legacy():
  reset();d=p.evaluate("()=>{const raw=JSON.parse(JSON.stringify(DEFAULT));raw.appMode='simple';raw.workPreset='quick';raw.resultMode='secureOffline';raw.identityMode='oneTimeCode';raw.diferencovany='ANO';raw.splitGenerate=true;raw.layout='scroll';raw.sourceUseMode='grammar';replaceStateFromUntrusted(raw);normalizeLoadedState(state);enforceModeConstraints();return {mode:state.appMode,result:state.resultMode,identity:state.identityMode,diff:state.diferencovany,split:state.splitGenerate,layout:state.layout,source:state.sourceUseMode}}");assert d['mode']=='advanced' or (d['result']=='instant' and d['identity']=='name' and d['diff']=='NE' and not d['split'] and d['layout']=='tabs' and d['source']=='auto'),d;return d
 record('legacy-incompatible-simple-state-is-not-hidden',legacy)
 def detail():
  reset();p.evaluate("()=>{state.appMode='simple';state.workPreset='quick';applySimpleDefaults();state.typyCviceni=['translation','multiple choice'];state.pocet=2;state.exerciseDetail=false;state.exerciseConfig=[{typ:'ordering',pocetOtazek:30,body:999,manualMode:true}];toggleExDetail()}");d=p.evaluate("({detail:state.exerciseDetail,types:state.exerciseConfig.map(x=>x.typ),manual:state.exerciseConfig.map(x=>x.manualMode),count:state.exerciseConfig.length})");assert d['detail'] and d['count']==2 and d['types']==['translation','multiple choice'] and d['manual']==[False,False],d;return d
 record('simple-detail-rebuilds-from-visible-selection',detail)
finally:h.close()
