#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {parse} from 'acorn';
const APP_ID='generator',CORE_VERSION='1.0.0',CORE_DIR=path.resolve('vendor',`ghrab-ai-core-${CORE_VERSION}`),CORE_FILE=`ghrab-ai-core-${CORE_VERSION}.js`,CORE_MANIFEST=`ghrab-ai-core-manifest-${CORE_VERSION}.json`;
const readJson=file=>JSON.parse(fs.readFileSync(file,'utf8')),fail=message=>{console.error('❌ '+message);process.exit(1)},sha=file=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
function stripJsComments(source,file){const comments=[];try{parse(source,{ecmaVersion:'latest',sourceType:'script',allowAwaitOutsideFunction:true,onComment:comments,ranges:true})}catch(error){fail(`nelze analyzovat ${file} pro build kompakci: ${error.message}`)}if(!comments.length)return source;let out='',cursor=0;for(const comment of comments){out+=source.slice(cursor,comment.start);const raw=source.slice(comment.start,comment.end);if(comment.type==='Block'){const lines=(raw.match(/\n/g)||[]).length;out+=lines?'\n'.repeat(lines):' '}cursor=comment.end}return out+source.slice(cursor)}
function stripCssComments(source,file){let out='',quote='',escaped=false;for(let i=0;i<source.length;i++){const char=source[i];if(quote){out+=char;if(escaped){escaped=false;continue}if(char==='\\\\'){escaped=true;continue}if(char===quote)quote='';continue}if(char==='"'||char==="'"){quote=char;out+=char;continue}if(char==='/'&&source[i+1]==='*'){const end=source.indexOf('*/',i+2);if(end===-1)fail(`neuzavřený CSS komentář v ${file}`);out+=' ';i=end+1;continue}out+=char}return out}
function compactHtmlShell(source){const lines=source.replace(/<!--(?!\s*BUILD:)[\s\S]*?-->/g,'').split('\n').map(line=>line.trim());const out=[];for(const line of lines){if(!line&&(!out.length||out[out.length-1]===''))continue;out.push(line)}return out.join('\n')}
function copyDir(src,dest){if(!fs.existsSync(src))return;fs.mkdirSync(dest,{recursive:true});for(const entry of fs.readdirSync(src,{withFileTypes:true})){const from=path.join(src,entry.name),to=path.join(dest,entry.name);entry.isDirectory()?copyDir(from,to):fs.copyFileSync(from,to)}}
function assertVersionSync(){const pkg=readJson('package.json'),core=fs.readFileSync('src/js/01-core.js','utf8'),sw=fs.readFileSync('public/sw.js','utf8'),manifest=readJson('public/manifest.webmanifest');const versions={package:String(pkg.version||'').trim(),release:core.match(/version:\s*['"]([^'"]+)['"]/)?.[1]||'',sw:sw.match(/CACHE_NAME\s*=\s*['"][^'"]*v([^'"]+)['"]/)?.[1]||'',manifest:String(manifest.version||'').trim()};if(manifest.id!=='./'||manifest.start_url!=='./')fail('PWA manifest musí mít stabilní id a start_url');if(Object.values(versions).some(v=>!v)||new Set(Object.values(versions)).size!==1)fail('nesedí verze napříč projektem');return versions.package}
for(const f of [CORE_FILE,CORE_MANIFEST])if(!fs.existsSync(path.join(CORE_DIR,f)))fail('chybí Core artefakt '+f);const coreManifest=readJson(path.join(CORE_DIR,CORE_MANIFEST));if(coreManifest.coreVersion!==CORE_VERSION||coreManifest.artifacts?.[CORE_FILE]?.sha256!==sha(path.join(CORE_DIR,CORE_FILE)))fail('GHRAB AI Core neprošel SHA-256 kontrolou');
const DIST_DIR=path.resolve('dist'),DIST=path.join(DIST_DIR,'index.html'),PUBLIC_DIR=path.resolve('public'),appVersion=assertVersionSync();fs.rmSync(DIST_DIR,{recursive:true,force:true});fs.mkdirSync(DIST_DIR,{recursive:true});
const ACORN_DIR=path.resolve('node_modules','acorn'),ACORN_BROWSER=path.join(ACORN_DIR,'dist','acorn.js'),ACORN_LICENSE=path.join(ACORN_DIR,'LICENSE');
if(!fs.existsSync(ACORN_BROWSER)||!fs.existsSync(ACORN_LICENSE))fail('chybí lokální CSP-safe JavaScript parser Acorn; spusť npm ci');
const shell=compactHtmlShell(fs.readFileSync('src/shell.html','utf8')),styles=stripCssComments(fs.readFileSync('src/styles.css','utf8'),'src/styles.css'),jsDir='src/js',migrationTombstones=new Set(['13-secure-export.js','14-test-html-builders.js']);
const jsFiles=fs.readdirSync(jsDir).filter(f=>f.endsWith('.js')&&!migrationTombstones.has(f)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})),mainParts=jsFiles.filter(f=>!f.startsWith('50-')&&!f.startsWith('60-'));
const inlineScriptTag=file=>`<script type="application/ghrab-protected" data-ghrab-protected data-source="${file}">\n${stripJsComments(fs.readFileSync(path.join(jsDir,file),'utf8'),file)}\n</script>`;
const coreTag=`<script type="application/ghrab-protected" data-ghrab-protected data-source="${CORE_FILE}">\n${fs.readFileSync(path.join(CORE_DIR,CORE_FILE),'utf8')}\n</script>`;
const jsMainTags=[coreTag,...mainParts.map(inlineScriptTag)].join('\n'),jsCsTag=inlineScriptTag('50-cs-module.js'),jsPwaTag=inlineScriptTag('60-pwa.js');
const requestedBuildTime=String(process.env.GHRAB_BUILD_TIME||'').trim();
const buildTime=requestedBuildTime?new Date(requestedBuildTime).toISOString():new Date().toISOString();
if(requestedBuildTime&&Number.isNaN(Date.parse(requestedBuildTime)))fail('GHRAB_BUILD_TIME musí být platný ISO-8601 čas');
let out=shell.replace('{{STYLES}}',()=>styles).replace('{{APP_VERSION}}',()=>appVersion).replace('{{JS_MAIN_TAGS}}',()=>jsMainTags).replace('{{JS_CS_TAG}}',()=>jsCsTag).replace('{{JS_PWA_TAG}}',()=>jsPwaTag);out=out.replace(/(<html[^>]*>)/i,`$1\n<!-- BUILD: ${buildTime} -->`);fs.writeFileSync(DIST,out,'utf8');copyDir(PUBLIC_DIR,DIST_DIR);copyDir(path.resolve('src','features'),path.join(DIST_DIR,'features'));fs.mkdirSync(path.join(DIST_DIR,'vendor'),{recursive:true});fs.copyFileSync(ACORN_BROWSER,path.join(DIST_DIR,'vendor','acorn.js'));fs.copyFileSync(ACORN_LICENSE,path.join(DIST_DIR,'vendor','acorn-LICENSE.txt'));
const operations=readJson(path.join(DIST_DIR,'ai-operations.json'));if(operations.appId!==APP_ID||operations.appVersion!==appVersion||operations.coreVersion!==CORE_VERSION||operations.operations.length!==11)fail('neplatný ai-operations.json');const appSource=mainParts.map(f=>fs.readFileSync(path.join(jsDir,f),'utf8')).join('\n');for(const op of operations.operations)if(!appSource.includes(`'${op.operation}'`)&&!appSource.includes(`"${op.operation}"`))fail('integrace neobsahuje operaci '+op.operation);
const template=path.resolve('studio/app-manifest.template.json');if(fs.existsSync(template)){const text=fs.readFileSync(template,'utf8').replaceAll('__APP_VERSION__',appVersion).replaceAll('__BUILD_TIME__',buildTime);const manifest=JSON.parse(text);const status=`${manifest.status?.cs||''} ${manifest.status?.en||''}`.toLowerCase();if(/produk|production/.test(status))fail('manifest před schválením nesmí deklarovat produkci');if(manifest.aiCore?.coreVersion!==CORE_VERSION||manifest.aiCore?.serverReady!==true||manifest.aiCore?.conformancePassed!==true)fail('studio-manifest nemá P1 AI Core metadata');fs.writeFileSync(path.join(DIST_DIR,'studio-manifest.json'),text)}
console.log(`✅ Generátor ${appVersion}: Core ${CORE_VERSION} SHA-256 OK · ${operations.operations.length} operací · ${mainParts.length+2} initial modulů + 2 lazy features · ${(fs.statSync(DIST).size/1024).toFixed(1)} kB`);

// P2: canonical cross-application platform post-processing.
await import("./apply-ghrab-platform.mjs");
